
package com.uy.agenciaWsClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceImm", targetNamespace = "http://imm.uy.com/", wsdlLocation = "http://localhost:8080/servlet/WebServiceImm?wsdl")
public class WebServiceImm_Service
    extends Service
{

    private final static URL WEBSERVICEIMM_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICEIMM_EXCEPTION;
    private final static QName WEBSERVICEIMM_QNAME = new QName("http://imm.uy.com/", "WebServiceImm");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/servlet/WebServiceImm?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICEIMM_WSDL_LOCATION = url;
        WEBSERVICEIMM_EXCEPTION = e;
    }

    public WebServiceImm_Service() {
        super(__getWsdlLocation(), WEBSERVICEIMM_QNAME);
    }

    public WebServiceImm_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICEIMM_QNAME, features);
    }

    public WebServiceImm_Service(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICEIMM_QNAME);
    }

    public WebServiceImm_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICEIMM_QNAME, features);
    }

    public WebServiceImm_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceImm_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceImm
     */
    @WebEndpoint(name = "WebServiceImmPort")
    public WebServiceImm getWebServiceImmPort() {
        return super.getPort(new QName("http://imm.uy.com/", "WebServiceImmPort"), WebServiceImm.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceImm
     */
    @WebEndpoint(name = "WebServiceImmPort")
    public WebServiceImm getWebServiceImmPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://imm.uy.com/", "WebServiceImmPort"), WebServiceImm.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICEIMM_EXCEPTION!= null) {
            throw WEBSERVICEIMM_EXCEPTION;
        }
        return WEBSERVICEIMM_WSDL_LOCATION;
    }

}
