
package com.uy.agenciaWsClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceImm", targetNamespace = "http://imm.uy.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceImm {


    /**
     * 
     * @param matricula
     * @param minutos
     * @param inicioEst
     * @param agencia
     * @param fechaVenta
     * @return
     *     returns com.uy.agenciaWsClient.TicketsEst
     */
    @WebMethod(operationName = "alta_tiket")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "alta_tiket", targetNamespace = "http://imm.uy.com/", className = "com.uy.agenciaWsClient.AltaTiket")
    @ResponseWrapper(localName = "alta_tiketResponse", targetNamespace = "http://imm.uy.com/", className = "com.uy.agenciaWsClient.AltaTiketResponse")
    public TicketsEst altaTiket(
        @WebParam(name = "agencia", targetNamespace = "")
        String agencia,
        @WebParam(name = "matricula", targetNamespace = "")
        String matricula,
        @WebParam(name = "fecha_venta", targetNamespace = "")
        String fechaVenta,
        @WebParam(name = "inicio_est", targetNamespace = "")
        String inicioEst,
        @WebParam(name = "minutos", targetNamespace = "")
        int minutos);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "baja_tiket")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "baja_tiket", targetNamespace = "http://imm.uy.com/", className = "com.uy.agenciaWsClient.BajaTiket")
    @ResponseWrapper(localName = "baja_tiketResponse", targetNamespace = "http://imm.uy.com/", className = "com.uy.agenciaWsClient.BajaTiketResponse")
    public String bajaTiket(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
